In [122]:
import json
import pandas as pd
from pandas.io.json import json_normalize

In [116]:
import os
data = pd.read_csv('weather/weatherlist.txt', sep=",", header=None,delim_whitespace=True)
data=data.transpose()

In [117]:
x=data[0].str.split(',', expand=True)
x=x.transpose()
x

      0
0   ATL
1   CLT
2   DEN
3   DFW
4   EWR
5   IAH
6   JFK
7   LAS
8   LAX
9   MCO
10  MIA
11  ORD
12  PHX
13  SEA
14  SFO

In [118]:
weatherdf=pd.DataFrame()

type(weatherdf)

pandas.core.frame.DataFrame

In [14]:
with open('weather/ATL/2016-1.json') as f:
    d = json.load(f)

#lets put the data into a pandas df
#clicking on raw_nyc_phil.json under "Input Files"
#tells us parent node is 'programs'
nycphil = json_normalize(d['data']['weather'])
nycphil.head(5)

,astronomy,date,hourly,maxtempC,maxtempF,mintempC,mintempF,sunHour,totalSnow_cm,uvIndex
0,"[{'moon_phase': 'Waning Gibbous', 'moonrise': ...",2016-01-01,"[{'windspeedKmph': '11', 'FeelsLikeF': '46', '...",11,51,5,42,7.5,0.0,0
1,"[{'moon_phase': 'Last Quarter', 'moonrise': '0...",2016-01-02,"[{'windspeedKmph': '15', 'FeelsLikeF': '34', '...",9,48,2,35,9.0,0.0,0
2,"[{'moon_phase': 'Last Quarter', 'moonrise': '0...",2016-01-03,"[{'windspeedKmph': '10', 'FeelsLikeF': '37', '...",11,51,3,38,7.5,0.0,0
3,"[{'moon_phase': 'Last Quarter', 'moonrise': '0...",2016-01-04,"[{'windspeedKmph': '13', 'FeelsLikeF': '37', '...",8,46,-1,31,9.5,0.0,0
4,"[{'moon_phase': 'Waning Crescent', 'moonrise':...",2016-01-05,"[{'windspeedKmph': '12', 'FeelsLikeF': '28', '...",6,43,1,33,10.0,0.0,0

In [125]:
df=[]
dd=pd.DataFrame()

In [126]:
for i in x[0]:
    path='weather/'+i
    for j in os.listdir(path):
        if('2016' in j):
            with open('weather/'+i+'/'+j) as f:
                d = json.load(f)
                data = json_normalize(d['data']['weather'])
                data=data[['date','hourly']]
                data['airport']=i
                works_data = json_normalize(data=d['data']['weather'], record_path='hourly', errors='ignore')
                works_data['airport'] =i
                dd=dd.append(works_data)

In [130]:
finalweatherdata2016=dd[['airport','windspeedKmph','winddirDegree','weatherCode','precipMM','visibility',
'pressure',
'cloudcover',
'DewPointF',
'WindGustKmph',
'tempF',
'WindChillF',
'humidity',
'time']]

In [141]:
#finalweatherdata2016

In [132]:
dd2017=pd.DataFrame()
for i in x[0]:
    path='weather/'+i
    for j in os.listdir(path):
        if('2017' in j):
            with open('weather/'+i+'/'+j) as f:
                d = json.load(f)
                data = json_normalize(d['data']['weather'])
                data=data[['date','hourly']]
                data['airport']=i
                works_data = json_normalize(data=d['data']['weather'], record_path='hourly', errors='ignore')
                works_data['airport'] =i
                dd2017=dd2017.append(works_data)

In [134]:
finalweatherdata2017=dd2017[['airport','windspeedKmph','winddirDegree','weatherCode','precipMM','visibility',
'pressure',
'cloudcover',
'DewPointF',
'WindGustKmph',
'tempF',
'WindChillF',
'humidity',
'time']]

In [137]:
#finalweatherdata2017

In [139]:
finalweatherdata=pd.concat([finalweatherdata2016,finalweatherdata2017])

In [143]:
#finalweatherdata.to_csv("weatherdata.csv")
finalweatherdata

,airport,windspeedKmph,winddirDegree,weatherCode,precipMM,visibility,pressure,cloudcover,DewPointF,WindGustKmph,tempF,WindChillF,humidity,time
0,ATL,11,318,176,0.1,10,1023,100,47,17,49,46,91,0
1,ATL,13,317,176,0.0,10,1023,100,44,22,46,42,92,100
2,ATL,14,315,122,0.0,10,1023,100,41,26,43,38,92,200
3,ATL,16,314,122,0.0,10,1023,100,38,30,40,33,93,300
4,ATL,17,314,122,0.0,10,1023,100,38,30,40,33,93,400
5,ATL,17,315,122,0.0,10,1024,100,38,29,40,33,93,500
6,ATL,18,315,122,0.0,10,1024,100,38,28,40,32,93,600
7,ATL,18,317,122,0.0,10,1024,100,38,26,41,33,93,700
8,ATL,17,318,122,0.0,10,1025,100,38,23,42,34,92,800
9,ATL,17,319,122,0.0,10,1025,100,39,20,42,35,92,900
10,ATL,17,318,122,0.0,10,1025,100,38,20,44,36,88,1000
11,ATL,17,317,122,0.0,10,1025,100,38,20,45,37,84,1100
12,ATL,17,317,122,0.0,10,1025,100,38,20,47,38,81,1200
13,ATL,17,317,122,0.0,10,1025,100,38,21,47,38,79,1300
14,ATL,17,317,122,0.0,10,1025,100,38,21,48,39,76,1400
15,ATL,17,317,122,0.0,10,1024,100,37,22,49,39,74,1500
16,ATL,17,318,122,0.0,10,1024,100,37,24,48,39,74,1600
17,ATL,17,318,122,0.0,10,1024,100,36,25,46,39,73,1700
18,ATL,17,319,122,0.0,10,1024,100,36,26,45,38,73,1800
19,ATL,17,318,122,0.0,10,1025,100,35,26,44,37,72,1900
20,ATL,17,317,122,0.0,10,1025,100,34,26,43,37,71,2000
21,ATL,16,316,122,0.0,10,1026,100,33,26,42,36,71,2100
22,ATL,16,317,122,0.0,10,1026,95,33,25,41,35,72,2200
23,ATL,16,318,122,0.0,10,1026,91,33,24,41,35,74,2300
24,ATL,15,319,122,0.0,10,1026,86,33,23,40,34,76,0
25,ATL,16,320,122,0.0,10,1026,81,33,23,39,33,78,100
26,ATL,16,321,116,0.0,10,1026,76,33,23,38,32,80,200
27,ATL,16,322,116,0.0,10,1026,71,33,23,38,31,83,300
28,ATL,16,319,116,0.0,10,1026,79,32,23,37,30,83,400
29,ATL,16,316,122,0.0,10,1026,88,32,23,36,29,84,500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
690,SFO,23,272,122,0.0,10,1015,87,58,25,61,61,90,1800
691,SFO,22,271,122,0.0,10,1015,91,58,24,60,60,91,1900
692,SFO,21,271,122,0.0,10,1014,95,58,23,60,60,93,2000
693,SFO,20,271,122,0.0,10,1014,99,58,22,59,59,94,2100
694,SFO,19,271,122,0.0,10,1014,99,58,21,59,59,94,2200
695,SFO,18,271,122,0.0,10,1014,100,58,20,59,59,95,2300
696,SFO,17,271,122,0.0,10,1014,100,58,19,59,58,95,0
697,SFO,17,273,122,0.0,10,1014,100,57,18,59,57,96,100
698,SFO,16,274,122,0.0,10,1014,100,57,18,58,56,96,200
699,SFO,16,276,122,0.0,10,1014,100,57,18,58,55,97,300
700,SFO,15,283,122,0.0,10,1014,100,56,16,57,55,97,400
701,SFO,14,289,143,0.0,10,1014,100,56,15,57,55,97,500
702,SFO,13,296,143,0.0,10,1014,100,56,14,57,55,97,600
703,SFO,11,302,143,0.0,10,1015,100,56,13,57,55,96,700
704,SFO,10,308,122,0.0,10,1015,99,56,12,57,56,95,800
705,SFO,8,313,122,0.0,10,1015,99,55,10,57,56,94,900
706,SFO,11,310,122,0.0,10,1015,90,55,13,58,57,91,1000
707,SFO,13,307,113,0.0,10,1016,81,55,15,59,59,88,1100
708,SFO,16,304,113,0.0,10,1016,73,55,18,60,60,85,1200
709,SFO,18,299,113,0.0,10,1015,54,56,20,62,62,80,1300
710,SFO,21,295,113,0.0,10,1015,35,56,22,64,64,76,1400
711,SFO,23,291,113,0.0,10,1015,16,56,25,65,65,71,1500
712,SFO,24,292,113,0.0,10,1015,11,56,26,66,66,70,1600
713,SFO,25,293,113,0.0,10,1014,5,57,27,67,67,69,1700
714,SFO,26,294,113,0.0,10,1014,0,57,27,68,68,68,1800
715,SFO,26,296,113,0.0,10,1014,0,57,27,67,67,70,1900
716,SFO,26,298,113,0.0,10,1014,0,58,27,67,67,71,2000
717,SFO,26,300,113,0.0,10,1014,0,58,27,67,67,73,2100
718,SFO,23,302,113,0.0,10,1014,0,58,25,66,66,74,2200
719,SFO,20,303,113,0.0,10,1014,0,58,22,66,66,75,2300